### PR TITLE
Make it more capital framework-y

### PR DESCRIPTION
**Pull request by contolini**
This is #28 but merged into master with some additional improvements. It needs some clean up but it's a good start for now.

### CODE REVIEW

**Comment by sleitner** [comment]
This looks awesome! 

The only problem I've found is that we do lose the title in the header.

**Comment by contolini** [comment]
That's not good. :expressionless:

**Comment by contolini** [comment]
Which title is missing?

**Comment by contolini** [comment]
See if that latest commit fixes it.

**Comment by sleitner** [comment]
great! merging

**Pull request merged**
