### PR TITLE
Move metadata into expandables

### PR DESCRIPTION
**Pull request by contolini**
@sleitner @montedesai What if we move every section into an expandable and open the first two by default?

screen shot 2015-08-05 at 1 15 06 pm

### CODE REVIEW

**Comment by sleitner** [comment]
That looks good to me, but @montedesai  had expressed some concern about empty sections cluttering things up(?). 

What do you and Monte think of moving the access request email blurb down into the access section?

**Comment by MonteDesai** [comment]
Only select users will be interested in the Admin and Compliance fields, so keeping them behind an expandable would work.

Most users will care about the content and access fields, so it would be good to show all of them (if they are populated) by default.

**Comment by sleitner** [comment]
Cool, all set?

**Comment by contolini** [comment]
I'm out today so tweak this if it needs tweakin'.

On Thursday, August 6, 2015, Sam Leitner notifications@github.com wrote:

> Cool, all set?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sleitner/ckanext-cfpb-extrafields/pull/43#issuecomment-128399073
> .

## 

Chris

**Pull request merged**
